#!/bin/bash
case $(uname -m) in
  x86_64)
    sh x86_64.sh; exit 0
  ;;
esac

case $(uname -m) in
  aarch64)
    sry but your arch is not supported bozo
  ;;
esac

case $(uname -m) in
  i686)
    sry but your arch is not supported bozo,  try upgrading your sys
  ;;
esac

echo "WE CANT RECOGNISE YOUR SYSTEM ARCH. "; exit 1
